spring.application.name=workingsystem
api.baseUrl=http://localhost:8080

# --- Database Config ---
spring.datasource.url=jdbc:sqlserver://localhost;databaseName=workingSystem;encrypt=false;trustServerCertificate=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# --- JPA / Hibernate Config ---
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=none

# --- Flyway Config ---
spring.flyway.enabled=true
spring.flyway.check-location=true
spring.flyway.locations=classpath:db/migration
#logging.level.org.flywaydb=DEBUG

# --- Logging & Others ---
spring.output.ansi.enabled=ALWAYS
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %highlight(%logger{36}) - %msg%n

# Cloudinary & Multipart Config (Gi? nguy�n c?a b?n)
cloudinary.api_secret=y2DZVY_jRbHPeHL0xfeS2SC9b78
cloudinary.api_key=375869887957666
cloudinary.cloud_name=dudr7ajma

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB